<h3 class="blog-link"><a href="http://www.storbital.com/blog/posts/18">Product News</a></h3>
<p>Upon the release of Storbital, we will keep our users updated with all the latest netbook news and reviews. We want all of our users to be as clued up about the netbook and tablet markets as we are, so they can make the most informed decision when buying a portable computing device.</p>
<p>So keep following this catergory for all the latest netbook news.</p>
