<?php
	echo $form->create('User', array( 'url' => array( 'action' => 'register', 'id' => 'registration-form') ) );
	echo $form->input('username', array(
		'after' => $form->error('username_unique', 'The username is taken. Please try another.'),
		'id' =>'username'
	));
	echo $form->input('password', array('id' =>'password'));
	echo $form->input('confirm_password', array( 'type' => 'password' ) );
	echo $form->input('email');
	echo $form->end('Register');
?>
