<?php
echo $form->create('Review', array('action' => 'add'));
if(!isset($products)) {
	echo $form->input('product_id', array('type' => 'hidden', 'value' => $product['Product']['id']));
} else {
	echo $form->input('product_id');
}
echo $form->input('title');
echo $form->input('body', array('type' => 'textarea'));
?>
<div class="input rating">
	<label>Rating</label>
	<?php echo $storbital->rate('Review', 'rating'); ?>
</div>
<?php echo $form->end('Submit Review'); ?>