<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $html->charset();?>
	<title><?php echo $title_for_layout; ?></title>
	<meta name="robots" content="noindex,nofollow" />
<?php
	echo $html->meta('icon') . "\n\t";
	echo $html->css(array('storbital','admin_style', '/js/fancybox/jquery.fancybox-1.3.1.css')) . "\n\t";
	echo $html->script(array(
		'http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js',
		'jquery/jquery.jeditable.mini.js',
		'jquery/jquery-ui-1.8.min.js',
		'admin.js'
	))."\n";
	echo $scripts_for_layout;
?>
</head>
<body id="admin">
<div id="wrap">
	<div id="admin-header">
		<a id="admin-logo" href="/" title="Go to Storbital Homepage"><img src="/img/layout/storbital-logo-small.png" /></a>
		<? if(isset($user)):?>
		<p id="user-info">
			Welcome <strong><?=$user['User']['name'] ?></strong>, <a href="/users/logout">Logout</a>.
		</p>
		<? endif; ?>
	</div>
	<div id="admin-sidebar">
	<?php if(isset($user) && $user['User']['group_id'] < 3):?>
	<ul id="admin-menu">
		<li><a href="/admin/">Dashboard</a></li>
		<li>Products
			<ul>
				<li><a href="/admin/products/edit">Add Product</a></li>
				<li><a href="/admin/products">Manage Products</a></li>
			</ul>
		</li>
		<li>Links
			<ul>
				<li><a href="/admin/links/edit">Add Link</a></li>
				<li><a href="/admin/links">Manage Links</a></li>
			</ul>
		</li>
		<li>Other
			<ul>
				<li><?php echo $html->link('Graphics', array('controller' => 'gpus'))?></li>
				<li><?php echo $html->link('Manufacturers', array('controller' => 'manufacturers'))?></li>
				<li><?php echo $html->link('Processors', array('controller' => 'cpus', 'action' => 'index'));?></li>
				<li><?php echo $html->link('Retailers', array('controller' => 'retailers'))?></li>
			</ul>
		</li>
		<li>Users
			<ul>
				<li><a href="/admin/users/add">Add User</a></li>
			</ul>
		</li>
	</ul>
	<? endif; ?>
	</div>
	<div id="admin-content">
	<h2><?php echo $title_for_layout;?></h2>
	<?php echo $session->flash(); ?>
	<?php echo $content_for_layout; ?>
	</div>
</div>
<?php echo $js->writeBuffer(); ?>
</body>
</html>