<p>Use this page to add graphics cards/chips (GPUs) to the Stobital database.</p>
<?php echo $form->create('Gpu', array('action' => 'index', 'class' => 'admin-input-form')); ?>
<fieldset>
<legend>Add GPU</legend>
<?php
echo $form->input('name');
echo $form->input('full_name');
echo $form->input('url', array('label' => 'Info URL'));
echo $form->submit('Save');
?>
</fieldset>
<?php echo $form->end();?>
<?php echo $this->element('pagination'); ?>
<table class="list-table" cellpadding="0" cellspacing="0">
	<thead>
	<tr>
		<th><?php echo $paginator->sort('Name', 'name'); ?></th>
		<th>Full Name</th>
		<th>Info</th>
		<th># Products</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($gpus as $gpu) :?>
	<tr>
		<td><?php echo $gpu['Gpu']['name'];?></td>
		<td><?php echo $gpu['Gpu']['full_name'];?></td>
		<td><?php echo $html->link($html->image('icons/link_go.png',array('class' => 'inline-icon')),$gpu['Gpu']['url'], array('escape' => false));?></td>
		<td><?php
			echo $gpu['Gpu']['product_count'];
			if ($gpu['Gpu']['product_count'] == 0) {
				echo $html->link($html->image('icons/delete.png'),array(
					'action'=>'delete',
					$gpu['Gpu']['id']),
					array('class' =>' confirm_delete' ,'escape' => false));
			}
			?>
		</td>
	</tr>
	<?php endforeach; ?>
	</tbody>
</table>
</div>