<div>
<?php
echo $html->link('Add User', array('action' => 'add'));
?>
</div>
<hr />
<table width="100%">
    <tbody>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th></th>
        </tr>
<?php
if (!empty($users)) {
    foreach ($users as $i) {
        echo '<tr>';
        echo '  <td>'.$i['User']['id'].'</td>';
        echo '  <td>'.$i['User']['name'].'</td>';
        echo '  <td><a href="mailto: '.$i['User']['email'].'">'.$i['User']['email'].'</a></td>';
        echo '  <td class="actions">';
        echo $html->link('View', array('action' => 'view', $i['User']['id'])).' | ';
        echo $html->link('Edit', array('action' => 'edit', $i['User']['id'])).' | ';
        echo $html->link('Delete', array('action' => 'delete', $i['User']['id']), null, 'Are you sure you want to delete this user?');
        echo '  </td>';
        echo '</tr>';
    }
}
?>
    </tbody>
</table>