<?php
if(isset($shortlist)) {
	$prod->setShortlist($shortlist);
}
?>
<div id="share">
<div id="fb-root"></div>
<script type="text/javascript">
  window.fbAsyncInit = function() {
    FB.init({
      appId  : '180948576449',
      status : true, // check login status
      cookie : true, // enable cookies to allow the server to access the session
      xfbml  : true  // parse XFBML
    });
  };

  (function() {
    var e = document.createElement('script');
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script>
</div>
<div id="product-summary" class="content-box">
<h2><?php echo $product['Product']['name']; ?></h2>
<?php echo $storbital->image(
	$product['Manufacturer']['logo_dir'],
	$product['Manufacturer']['logo'],
	'normal',
	array('alt' => $product['Manufacturer']['name']));
?>
<p><?php echo ife($product['Cpu']['full_name'], $product['Cpu']['full_name']); ?>
<?php echo ife($product['Gpu']['full_name'], '<br/>'.$product['Gpu']['full_name']); ?>
</p>
<?php echo $storbital->image(
	$product['Product']['image_dir'],
	$product['Product']['image'],
	'large',
	array('class' => 'product-image'));
?>
<p class="product-rating">Product Rating:  <a class="review-link" href="#reviews">Leave your own review &gt;&gt;</a></p>
<fb:like href="http://buyersguide.umpcmedia.com<?=$html->url();?>"></fb:like>
<?php echo $prod->shortlist($product['Product']['id'], true); ?>
<p id="product-description"><?php echo nl2br($product['Product']['description']); ?></p>

</div>
<div id="product-info">
<div id="tabs">
<ul class="tabs">
	<li id="buy-tab"><a href="#buy" title="Compare and Buy">Compare and Buy</a></li>
	<li id="specs-tab"><a href="#specs" title="Specifications">Technical Specs</a></li>
	<li id="reviews-tab"><a href="#reviews" title="Product Reviews">Product Reviews</a></li>
</ul>
<div id="buy" class="tab content-box">
	<?php if(!empty($links)) :?>
	<p class="note">These are the prices of the <?php echo $product['Product']['name'];?> that we have from our trusted online retailers, click the "Buy" button will take you through to that retailers product page with no obligation to buy.</p>
	<table id="links" cellpadding="10" cellspacing="0">
	<?php foreach($links as $link): ?>
	<tr class="link-info">
		<td class="retailer-logo">
		<?php echo $storbital->image($link['Retailer']['logo_dir'], $link['Retailer']['logo']); ?>
		</td>
		<td class="link-name"><h3><a href="<?php echo $link['Link']['url'];?>"><?php if(isset($link['Link']['title'])) {
			echo $link['Link']['title'];
		} else {
			echo $product['Product']['name'];
		}?></a>
		</h3></td>
		<td class="price">
			<a class="price-link" href="<?php echo $link['Link']['url'];?>"><span class="from">From </span>
			<?php if($link['Link']['price_monthly'] == '0.00') :?>
				<span class="price"><?php echo $link['Region']['currency_symbol_html'].$link['Link']['price']; ?></span>
			<?php else: ?>
				<?php if(isset($link['Link']['price'])): ?>
					<?php echo $link['Region']['currency_symbol_html'].$link['Link']['price'];?>
				<?php endif;?>
				<span class="price"><?php echo $link['Region']['currency_symbol_html'].$link['Link']['price_monthly']; ?></span>
				<span class="monthly">a month</span>
			<?php endif;?>
			</a>
		</td>
		<td>
		<?php echo $html->link('Buy', $link['Link']['url'],
		array(
			'title' => 'Buy '.$product['Product']['name'].' from '.$link['Retailer']['name'],
			'class' => 'go-button'
		));?>
		</td>
	</tr>
	<tr class="retailer-info">
		<td colspan="2"><span title="Retailer Rating">Rating: </span></td>
		<?php if(!empty($link['Colour'])): ?>
			<td colspan="2"><span class="colour-label">Colours:</span>
				<?php foreach($link['Colour'] as $colour): ?>
				<span class="colour-cell" style="background-color: #<?php echo $colour['hex']; ?>" title="<?php echo $colour['name'];?>"></span>
				<?php endforeach;?>
			</td>
		<?php else: ?>
		 <td colspan="2"></td>
		<?php endif;?>
	</tr>
	<?php endforeach; ?>
	</table>
	<p class="note">Know of another place you can buy the <?php echo $product['Product']['name'];?>? <?php echo $html->link('You can submit it to us here', array('controller' => 'links', 'action' => 'add', $product['Product']['id']));?>.</p>
	<?php else:
		echo '<p class="no-links">There are no links currently for this product. '.$html->link('Add one now', array('controller' => 'links', 'action' => 'add', $product['Product']['id'])).'.</p>';
	endif;?>
</div>
<div id="specs" class="tab content-box">
	<?php $specs = $prod->specifications($product, $tagGroups); ?>
	<ul>
		<?php foreach($specs as $specParent => $specChildren): ?>
			<li><?php echo $specParent; ?>
			<ul>
				<?php if(is_array($specChildren)) : ?>
				<?php foreach($specChildren as $spec) : ?>
					<?php if(is_array($spec)) :?>
						<li><?php echo $text->toList($spec, 'or'); ?></li>
					<?php else: ?>
						<li><?php echo $spec; ?></li>
					<?php endif; ?>
				<?php endforeach; ?>
				<?php else: ?>
					<li><?php echo $specChildren; ?></li>
				<?php endif;?>
			</ul></li>
		<?php endforeach; ?>
	</ul>
</div>
<div id="reviews" class="tab content-box">Reviews</div>
</div>
</div>